#!/usr/bin/env python3
"""Regenerate the embedded endmember table from USGS Spectral Library 7.

Downloads ASCIIdata_splib07a.zip from the USGS ScienceBase release
(doi:10.5066/F7RR1WDJ), extracts the curated endmember list below, pairs each
spectrum with its spectrometer's wavelength grid, drops the archive's deleted-
point marker, and writes one CSV.

splib07 stores wavelengths in a separate file per spectrometer, keyed by the
code in each spectrum's filename (BECK = Beckman, 0.2-3.0 um; ASD = Analytical
Spectral Devices, 0.35-2.5 um). Pairing the wrong grid to a spectrum yields a
plausible-looking curve at entirely wrong wavelengths, so the mapping is
explicit here rather than inferred.

Usage:  python3 build_table.py > ../data/splib07_endmembers.csv
"""

import csv
import io
import os
import re
import sys
import subprocess
from pathlib import Path
import zipfile

ITEM = "586e8c88e4b0f5ce109fccae"
ARCHIVE_NAME = "ASCIIdata_splib07a.zip"
CACHE = os.path.expanduser("~/.cache/splib07/a.zip")
MANIFEST = Path(__file__).resolve().parents[3] / "manifests/build-inputs.toml"
ARTIFACT_KEY = "usgs/splib07/ASCIIdata_splib07a.zip"

# splib07 marks deleted/invalid channels with a large negative sentinel.
DELETED_MARKER = -1e30

# Trim the noisy far-infrared tail; nothing downstream uses beyond this.
MAX_NM = 2600.0

# Wavelength grid per spectrometer code appearing in the filenames.
GRIDS = {
    "BECK": "splib07a_Wavelengths_BECK_Beckman_0.2-3.0_microns.txt",
    "ASD": "splib07a_Wavelengths_ASD_0.35-2.5_microns_2151_ch.txt",
}

# (endmember id, splib07 filename stem, human description).
ENDMEMBERS = [
    ("OpenOcean", "splib07a_Seawater_Open_Ocean_SW2_lwch_BECKa_AREF",
     "Open-ocean seawater, low chlorophyll"),
    ("CoastalWater", "splib07a_Seawater_Coast_Chl_SW1_BECKa_AREF",
     "Coastal seawater with chlorophyll"),
    ("GreenVegetation", "splib07a_Aspen_Leaf-A_DW92-2_BECKa_AREF",
     "Green aspen leaf; the canonical red-edge spectrum"),
    ("DryVegetation", "splib07a_Grass_Golden_Dry_GDS480_ASDFRa_AREF",
     "Dry golden grass, non-photosynthetic"),
    ("Sand", "splib07a_Sand_GrndIsle1_no_oil_ASDFRa_AREF",
     "Beach sand, Grand Isle, uncontaminated"),
    ("Snow", "splib07a_Melting_snow_mSnw01a_ASDFRa_AREF",
     "Melting snow; splib07 has no dry/fresh snow spectrum"),
    ("WaterIce", "splib07a_H2O-Ice_GDS136_77K_BECKa_AREF",
     "Water ice at 77 K"),
    ("FreshBasalt", "splib07a_Basalt_fresh_BR93-46B_BECKb_AREF",
     "Fresh basalt; analogue for lunar mare and Mars dark terrain"),
    ("WeatheredBasalt", "splib07a_Basalt_weathered_BR93-43_BECKb_AREF",
     "Weathered basalt"),
    ("AridSoil", "splib07a_Stonewall_Playa_Dry_Mud_2001_ASDFRa_AREF",
     "Dried playa mud; the reddened arid-surface endmember for barren terrain"),
    ("Asphalt", "splib07a_Asphalt_GDS376_Blck_Road_old_ASDFRa_AREF",
     "Old black asphalt road; the dark half of an urban surface"),
    ("Concrete", "splib07a_Concrete_GDS375_Lt_Gry_Road_ASDFRa_AREF",
     "Light grey concrete road; the bright half of an urban surface"),
]


def ensure_archive():
    """Resolve through the Rust CLI (streaming, validated, mirror aware)."""
    command = ["starfield-datastore"]
    selection = ["--manifest", str(MANIFEST), "--key", ARTIFACT_KEY]
    if os.path.isfile(CACHE):
        # A failed legacy validation must not bypass the normal resolution path.
        subprocess.run(command + ["import", *selection, "--from", CACHE],
                       stdout=subprocess.DEVNULL, check=False)
    result = subprocess.run(command + ["fetch", *selection], check=True,
                            stdout=subprocess.PIPE, text=True)
    return result.stdout.strip()


def read_column(z, path):
    """splib07 ASCII: one header line, then one float per line."""
    text = z.read(path).decode("utf-8", "replace")
    return [float(line) for line in text.splitlines()[1:] if line.strip()]


def spectrometer_of(stem):
    if "BECK" in stem:
        return "BECK"
    if "ASD" in stem:
        return "ASD"
    raise SystemExit(f"cannot determine spectrometer for {stem}")


def main():
    z = zipfile.ZipFile(ensure_archive())
    members = {os.path.basename(n): n for n in z.namelist() if "/errorbars/" not in n}

    grids = {}
    for code, filename in GRIDS.items():
        microns = read_column(z, members[filename])
        grids[code] = [um * 1000.0 for um in microns]  # um -> nm

    out = csv.writer(sys.stdout)
    print(
        "# Endmember reflectance spectra from the USGS Spectral Library Version 7.\n"
        "# Source: Kokaly et al. (2017), USGS Data Series 1035, doi:10.5066/F7RR1WDJ\n"
        f"# Archive: ScienceBase item {ITEM}, {ARCHIVE_NAME}\n"
        "# Reflectance is AREF (absolute reflectance), dimensionless.\n"
        "# Wavelengths converted from micrometres to nanometres; deleted channels\n"
        f"# (splib07 sentinel < {DELETED_MARKER:g}) dropped; trimmed above {MAX_NM:g} nm.\n"
        "# Generated by scripts/build_table.py; do not hand-edit."
    )
    out.writerow(["endmember", "wavelength_nm", "reflectance"])

    for endmember, stem, description in ENDMEMBERS:
        filename = f"{stem}.txt"
        if filename not in members:
            raise SystemExit(f"{filename} missing from archive")
        values = read_column(z, members[filename])
        grid = grids[spectrometer_of(stem)]
        if len(values) != len(grid):
            raise SystemExit(
                f"{endmember}: {len(values)} samples but grid has {len(grid)}"
            )
        kept = 0
        for nm, reflectance in zip(grid, values):
            if reflectance <= DELETED_MARKER or nm > MAX_NM:
                continue
            out.writerow([endmember, f"{nm:.2f}", f"{reflectance:.6e}"])
            kept += 1
        print(f"  {endmember:<18} {kept:5d} channels  ({description})", file=sys.stderr)


if __name__ == "__main__":
    main()
