#!/usr/bin/env python3
"""Regenerate the embedded 1 nm TSIS-1 HSRS v2 table from LASP LISIRD.

Downloads the native-resolution spectrum in wavelength chunks, reduces each
chunk to 1 nm box means immediately, and discards it — the full native product
is ~105 MB over this range and never needs to exist on disk at once.

Box means are computed from the NATIVE product (0.001-0.01 nm sampling), not
from LISIRD's pre-smoothed `tsis1_hsrs_p1nm`. That is deliberate: a naive mean
of the 0.1 nm product's samples differs from the true 1 nm box mean by up to
1.1% across strong Fraunhofer lines, which is larger than the archive's own
0.3% radiometric uncertainty.

Usage:  python3 build_table.py > ../data/tsis1_hsrs_v2_1nm.csv
"""

import csv
import io
import sys
import urllib.request

# Native-resolution TSIS-1 HSRS v2. The `_p1nm` sibling is pre-smoothed; see above.
BASE = "https://lasp.colorado.edu/lisird/latis/dap/tsis1_hsrs.csv"

# Archive coverage is 202-2730 nm; use whole-nanometre bins inside that.
LO_NM = 202
HI_NM = 2730
CHUNK_NM = 100
TIMEOUT_S = 300


def fetch(lo, hi):
    """Native samples in [lo, hi] as (wavelength_nm, irradiance, uncertainty)."""
    url = f"{BASE}?&wavelength>={lo}&wavelength<={hi}"
    with urllib.request.urlopen(url, timeout=TIMEOUT_S) as response:
        text = response.read().decode("utf-8")
    reader = csv.reader(io.StringIO(text))
    next(reader)  # header
    for row in reader:
        if len(row) >= 3:
            yield float(row[0]), float(row[1]), float(row[2])


def box_means():
    """1 nm box means over the archive range, in ascending wavelength order."""
    for chunk_lo in range(LO_NM, HI_NM, CHUNK_NM):
        chunk_hi = min(chunk_lo + CHUNK_NM, HI_NM)
        # Overlap by nothing: bins are [n, n+1), so a chunk owns [chunk_lo, chunk_hi).
        bins = {n: [0.0, 0.0, 0] for n in range(chunk_lo, chunk_hi)}
        for wavelength, irradiance, uncertainty in fetch(chunk_lo, chunk_hi):
            n = int(wavelength)
            if n in bins and wavelength < n + 1:
                acc = bins[n]
                acc[0] += irradiance
                acc[1] += uncertainty
                acc[2] += 1
        for n in range(chunk_lo, chunk_hi):
            total_irradiance, total_uncertainty, count = bins[n]
            if count == 0:
                print(f"gap: no native samples in [{n}, {n + 1})", file=sys.stderr)
                continue
            yield n, total_irradiance / count, total_uncertainty / count, count
        print(f"  {chunk_lo}-{chunk_hi} nm done", file=sys.stderr)


def main():
    out = csv.writer(sys.stdout)
    print(
        "# TSIS-1 Hybrid Solar Reference Spectrum (HSRS) version 2, "
        "resampled to 1 nm box means.\n"
        "# Source: Coddington et al. (2023), Earth and Space Science, "
        "doi:10.1029/2022EA002637\n"
        f"# Archive: LASP LISIRD, {BASE} (native 0.001-0.01 nm sampling)\n"
        "# Method: unweighted mean of every native sample falling in "
        "[n, n+1) nm; bin labelled by its lower edge.\n"
        "# Irradiance is solar spectral irradiance at 1 AU, W m^-2 nm^-1, "
        "solar-minimum conditions between cycles 24 and 25.\n"
        "# Archive uncertainty is 0.3% over 460-2365 nm and 1.3% outside it.\n"
        "# Generated by scripts/build_table.py; do not hand-edit."
    )
    out.writerow(
        ["wavelength_nm", "irradiance_w_m2_nm", "uncertainty_w_m2_nm", "n_samples"]
    )
    for n, irradiance, uncertainty, count in box_means():
        out.writerow([n, f"{irradiance:.6e}", f"{uncertainty:.3e}", count])


if __name__ == "__main__":
    main()
