//! Hipparcos-derived bright-star supplement for Gaia DR3.
//!
//! Gaia's CCDs saturate near `G ≈ 3` and astrometry remains degraded out to
//! `G ≈ 6`; even at `G ≤ 12` the catalog is missing or unreliable for many
//! pre-Gaia-era bright stars that Hipparcos resolves cleanly. This module
//! ships an embedded CSV of every Hipparcos entry (`Hp ≤ 9`) that has no
//! Gaia DR3 counterpart within 5″ of its J2016 position, materializes them
//! as [`Dr3Entry`]s on demand, and inserts them into a live
//! [`crate::Dr3Catalog`] via [`Dr3Catalog::augment_missing`].
//!
//! # Provenance
//!
//! The embedded supplement was generated by the `hipparcos-gaia-match`
//! binary in `starfield-gaia-tools` against a paginated TAP fetch of the
//! DR3 bright end (`G ≤ 12`). Re-running that binary with `--supplement
//! crates/gaia/data/dr3-bright-star-supplement.csv` regenerates the file
//! using the latest TAP data.
//!
//! # ID masking
//!
//! Real DR3 source IDs encode `(HEALPix12 << 35) | run_id`; HEALPix12 has
//! ~2·10⁸ cells, so the maximum legitimate `source_id` is roughly 6.92·10¹⁸,
//! comfortably below 2⁶³ = 9.22·10¹⁸. Supplement entries set bit 63 and
//! place the original Hipparcos `HIP` number in the low 31 bits:
//!
//! ```text
//! synthetic_source_id = 0x8000_0000_0000_0000 | (hip & 0x7FFF_FFFF)
//! ```
//!
//! Use [`is_supplement_source_id`] to detect supplement entries and
//! [`decode_supplement_hip`] to recover the HIP number. Supplement IDs are
//! disjoint from any real Gaia DR3 ID, so a HashMap keyed by `source_id`
//! never collides between the two populations.
//!
//! # Missing fields
//!
//! Hipparcos doesn't carry a Gaia-equivalent for most DR3 columns, so
//! supplement entries populate **only**:
//!
//! - `core.source_id` (synthetic, see above)
//! - `core.solution_id` = 0
//! - `core.ref_epoch` = 2016.0 (matches DR3)
//! - `core.ra`, `core.dec` — Hipparcos position propagated to J2016 via
//!   Hipparcos proper motion
//! - `core.parallax`, `core.pmra`, `core.pmdec` — from Hipparcos
//! - `core.l`, `core.b` — computed from RA/Dec via the J2000 galactic
//!   transform
//! - `core.ecl_lon`, `core.ecl_lat` — computed via the J2000 obliquity
//! - `core.phot_g_mean_mag` — fitted from Hipparcos `Hp` and `B-V` via the
//!   regression baked into the embedded CSV header
//!
//! Everything else is `None` / `Default::default()`. In particular:
//!
//! - **No BP, RP, or BP-RP**: Hipparcos has no Gaia BP/RP-equivalent
//!   measurement; renderers that need a color must fall back to `b_v` (or
//!   look it up via [`decode_supplement_hip`] and consult the Hipparcos
//!   catalog directly).
//! - **No flux errors, RUWE, IPD, GSP-Phot, RV, classifications, datalink
//!   flags** — all `None` / default.
//! - **`ra_error` / `dec_error` = 0.0** — placeholder; Hipparcos's milli-
//!   arcsecond astrometry is much better than typical Gaia bright-end
//!   errors but the fields are required by the schema, so we set 0 to
//!   indicate "unknown / not from Gaia".

use serde::{Deserialize, Serialize};
use starfield::{Result, StarfieldError};

use crate::common::core::{GaiaCore, VarFlag};
use crate::dr3::entry::{AstrometricExtra, Classifications, DataLinks, Dr3Entry, IpdQuality};

/// Sentinel bit set on every supplement-entry `source_id`. Real DR3 IDs cap
/// out around 6.92·10¹⁸ (well below 2⁶³), so any `source_id ≥ 1<<63` is a
/// supplement entry and never collides with a real one.
pub const SUPPLEMENT_SOURCE_ID_BIT: u64 = 1u64 << 63;

/// J2016.0 — DR3's nominal reference epoch; every supplement position is
/// already propagated to here, so callers don't need to PM-correct again.
pub const SUPPLEMENT_REF_EPOCH: f64 = 2016.0;

/// Encode a Hipparcos `HIP` number into a synthetic Gaia DR3 `source_id`.
/// The high bit (63) is set; the low 31 bits hold `hip` (HIP numbers max at
/// ~120000, so 31 bits is plenty).
pub const fn encode_supplement_source_id(hip: u32) -> u64 {
    SUPPLEMENT_SOURCE_ID_BIT | ((hip as u64) & 0x7FFF_FFFF)
}

/// Whether `source_id` came from this module's supplement (vs. a real Gaia
/// DR3 source).
pub const fn is_supplement_source_id(source_id: u64) -> bool {
    source_id & SUPPLEMENT_SOURCE_ID_BIT != 0
}

/// Recover the Hipparcos `HIP` number from a supplement-entry `source_id`,
/// or `None` if it isn't a supplement entry.
pub const fn decode_supplement_hip(source_id: u64) -> Option<u32> {
    if is_supplement_source_id(source_id) {
        Some((source_id & 0x7FFF_FFFF) as u32)
    } else {
        None
    }
}

/// The supplement CSV embedded at compile time. Each non-comment row matches
/// [`SupplementRow`].
const EMBEDDED_SUPPLEMENT_CSV: &str = include_str!("../../data/dr3-bright-star-supplement.csv");

/// One row of the embedded supplement CSV. Field names match the CSV header.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub struct SupplementRow {
    pub hip: u32,
    pub ra_j2016: f64,
    pub dec_j2016: f64,
    pub parallax_mas: Option<f64>,
    pub pmra_mas_yr: Option<f64>,
    pub pmdec_mas_yr: Option<f64>,
    pub b_v: Option<f64>,
    pub fitted_g_mag: f64,
}

/// Parse the embedded supplement into rows. Comment lines (starting with `#`)
/// and the header are skipped. Empty optional cells map to `None`.
pub fn parse_embedded_supplement() -> Result<Vec<SupplementRow>> {
    parse_supplement_csv(EMBEDDED_SUPPLEMENT_CSV)
}

fn parse_supplement_csv(csv: &str) -> Result<Vec<SupplementRow>> {
    let mut out = Vec::with_capacity(16_000);
    let mut header_seen = false;
    for (lineno, line) in csv.lines().enumerate() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if !header_seen {
            // First non-comment line is the column header — sanity-check it
            // so the embedded CSV and this code stay in sync.
            const EXPECTED: &str =
                "hip,ra_j2016,dec_j2016,parallax_mas,pmra_mas_yr,pmdec_mas_yr,b_v,fitted_g_mag";
            if line.trim() != EXPECTED {
                return Err(StarfieldError::DataError(format!(
                    "DR3 supplement CSV header mismatch at line {}: got {:?}, want {:?}",
                    lineno + 1,
                    line,
                    EXPECTED
                )));
            }
            header_seen = true;
            continue;
        }
        out.push(parse_row(line, lineno + 1)?);
    }
    Ok(out)
}

fn parse_row(line: &str, lineno: usize) -> Result<SupplementRow> {
    let parts: Vec<&str> = line.split(',').collect();
    if parts.len() != 8 {
        return Err(StarfieldError::DataError(format!(
            "DR3 supplement CSV line {}: expected 8 fields, got {}",
            lineno,
            parts.len()
        )));
    }
    let parse_req_u32 = |s: &str| {
        s.parse::<u32>()
            .map_err(|e| StarfieldError::DataError(format!("hip parse line {}: {}", lineno, e)))
    };
    let parse_req_f64 = |s: &str, field: &str| {
        s.parse::<f64>().map_err(|e| {
            StarfieldError::DataError(format!("{} parse line {}: {}", field, lineno, e))
        })
    };
    let parse_opt_f64 = |s: &str, field: &str| {
        if s.is_empty() {
            Ok(None)
        } else {
            s.parse::<f64>().map(Some).map_err(|e| {
                StarfieldError::DataError(format!("{} parse line {}: {}", field, lineno, e))
            })
        }
    };
    Ok(SupplementRow {
        hip: parse_req_u32(parts[0])?,
        ra_j2016: parse_req_f64(parts[1], "ra_j2016")?,
        dec_j2016: parse_req_f64(parts[2], "dec_j2016")?,
        parallax_mas: parse_opt_f64(parts[3], "parallax_mas")?,
        pmra_mas_yr: parse_opt_f64(parts[4], "pmra_mas_yr")?,
        pmdec_mas_yr: parse_opt_f64(parts[5], "pmdec_mas_yr")?,
        b_v: parse_opt_f64(parts[6], "b_v")?,
        fitted_g_mag: parse_req_f64(parts[7], "fitted_g_mag")?,
    })
}

/// Convert one supplement row into a [`Dr3Entry`]. Populates the minimal set
/// of fields described in the module docs; everything else is `None` /
/// `Default::default()`.
pub fn supplement_row_to_entry(r: &SupplementRow) -> Dr3Entry {
    let (l, b) = equatorial_to_galactic(r.ra_j2016, r.dec_j2016);
    let (ecl_lon, ecl_lat) = equatorial_to_ecliptic(r.ra_j2016, r.dec_j2016);

    let core = GaiaCore {
        source_id: encode_supplement_source_id(r.hip),
        solution_id: 0,
        ref_epoch: SUPPLEMENT_REF_EPOCH,
        random_index: None,
        ra: r.ra_j2016,
        ra_error: 0.0,
        dec: r.dec_j2016,
        dec_error: 0.0,
        ra_dec_corr: None,
        parallax: r.parallax_mas,
        parallax_error: None,
        pmra: r.pmra_mas_yr,
        pmra_error: None,
        pmdec: r.pmdec_mas_yr,
        pmdec_error: None,
        l,
        b,
        ecl_lon,
        ecl_lat,
        phot_g_mean_mag: r.fitted_g_mag,
        phot_g_mean_flux: None,
        phot_g_mean_flux_error: None,
        phot_g_n_obs: None,
        phot_variable_flag: VarFlag::default(),
        astrometric_n_obs_al: None,
        astrometric_excess_noise: None,
        astrometric_excess_noise_sig: None,
        astrometric_primary_flag: None,
        duplicated_source: None,
        matched_observations: None,
    };

    Dr3Entry {
        core,
        designation: None,
        pm: None,
        parallax_over_error: None,
        astrometric_extra: AstrometricExtra::default(),
        ipd: IpdQuality::default(),
        bp_rp: None,
        radial_velocity: None,
        gspphot: None,
        data_links: DataLinks::default(),
        classifications: Classifications::default(),
    }
}

// ----------------------------------------------------------------- coordinate helpers

/// J2000 obliquity of the ecliptic, degrees (IAU 2006 nominal).
const OBLIQUITY_DEG: f64 = 23.4392911;

/// J2000 north galactic pole and origin, IAU 1958 (degrees).
const RA_NGP_DEG: f64 = 192.85948;
const DEC_NGP_DEG: f64 = 27.12825;
const L_NCP_DEG: f64 = 122.93192;

/// Convert J2000 equatorial (RA, Dec) to galactic (l, b), in degrees.
fn equatorial_to_galactic(ra_deg: f64, dec_deg: f64) -> (f64, f64) {
    let ra = ra_deg.to_radians();
    let dec = dec_deg.to_radians();
    let ra_ngp = RA_NGP_DEG.to_radians();
    let dec_ngp = DEC_NGP_DEG.to_radians();
    let l_ncp = L_NCP_DEG.to_radians();

    let sin_b = dec.sin() * dec_ngp.sin() + dec.cos() * dec_ngp.cos() * (ra - ra_ngp).cos();
    let b = sin_b.clamp(-1.0, 1.0).asin();

    let y = dec.cos() * (ra - ra_ngp).sin();
    let x = dec.sin() * dec_ngp.cos() - dec.cos() * dec_ngp.sin() * (ra - ra_ngp).cos();
    let l = l_ncp - y.atan2(x);
    let mut l_deg = l.to_degrees();
    l_deg = l_deg.rem_euclid(360.0);
    (l_deg, b.to_degrees())
}

/// Convert J2000 equatorial (RA, Dec) to ecliptic (lon, lat), in degrees.
fn equatorial_to_ecliptic(ra_deg: f64, dec_deg: f64) -> (f64, f64) {
    let ra = ra_deg.to_radians();
    let dec = dec_deg.to_radians();
    let eps = OBLIQUITY_DEG.to_radians();

    let sin_lat = dec.sin() * eps.cos() - dec.cos() * eps.sin() * ra.sin();
    let lat = sin_lat.clamp(-1.0, 1.0).asin();
    let y = ra.sin() * eps.cos() + dec.tan() * eps.sin();
    let x = ra.cos();
    let mut lon_deg = y.atan2(x).to_degrees();
    lon_deg = lon_deg.rem_euclid(360.0);
    (lon_deg, lat.to_degrees())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn id_mask_round_trip() {
        let id = encode_supplement_source_id(42);
        assert!(is_supplement_source_id(id));
        assert_eq!(decode_supplement_hip(id), Some(42));
    }

    #[test]
    fn id_mask_disjoint_from_real_gaia_range() {
        // Real Gaia DR3 source_ids cap at ~6.92e18, well below 1<<63 = 9.22e18.
        // Pick a deliberately large legitimate-looking ID and confirm the
        // sentinel rejects it.
        let pseudo_real = 6_900_000_000_000_000_000u64;
        assert!(!is_supplement_source_id(pseudo_real));
        assert_eq!(decode_supplement_hip(pseudo_real), None);
    }

    #[test]
    fn embedded_supplement_parses() {
        let rows = parse_embedded_supplement().expect("embedded supplement parses");
        assert!(
            rows.len() > 1000,
            "expected thousands of rows, got {}",
            rows.len()
        );
        for r in &rows {
            assert!(r.hip > 0);
            assert!(r.ra_j2016 >= 0.0 && r.ra_j2016 <= 360.0);
            assert!(r.dec_j2016 >= -90.0 && r.dec_j2016 <= 90.0);
            assert!(r.fitted_g_mag.is_finite());
        }
    }

    #[test]
    fn supplement_row_to_entry_populates_core_correctly() {
        let row = SupplementRow {
            hip: 12345,
            ra_j2016: 180.5,
            dec_j2016: -23.0,
            parallax_mas: Some(15.0),
            pmra_mas_yr: Some(-100.0),
            pmdec_mas_yr: Some(50.0),
            b_v: Some(0.5),
            fitted_g_mag: 6.8,
        };
        let entry = supplement_row_to_entry(&row);
        assert_eq!(entry.core.ra, 180.5);
        assert_eq!(entry.core.dec, -23.0);
        assert_eq!(entry.core.parallax, Some(15.0));
        assert_eq!(entry.core.pmra, Some(-100.0));
        assert_eq!(entry.core.pmdec, Some(50.0));
        assert_eq!(entry.core.phot_g_mean_mag, 6.8);
        assert_eq!(entry.core.ref_epoch, SUPPLEMENT_REF_EPOCH);
        assert_eq!(decode_supplement_hip(entry.core.source_id), Some(12345));
        // Computed fields should be in valid ranges.
        assert!(entry.core.l >= 0.0 && entry.core.l <= 360.0);
        assert!(entry.core.b >= -90.0 && entry.core.b <= 90.0);
        assert!(entry.core.ecl_lon >= 0.0 && entry.core.ecl_lon <= 360.0);
        assert!(entry.core.ecl_lat >= -90.0 && entry.core.ecl_lat <= 90.0);
        // Missing fields should be None.
        assert!(entry.bp_rp.is_none());
        assert!(entry.radial_velocity.is_none());
    }

    /// Spot-check the equatorial→galactic transform against the known
    /// galactic center: (RA, Dec) ≈ (266.405, -28.936) → (l, b) ≈ (0, 0).
    #[test]
    fn equatorial_to_galactic_galactic_center() {
        let (l, b) = equatorial_to_galactic(266.40499, -28.93617);
        assert!(l.abs() < 0.1 || (l - 360.0).abs() < 0.1, "l = {}", l);
        assert!(b.abs() < 0.1, "b = {}", b);
    }

    /// And the equatorial→ecliptic transform: a point on the equator at
    /// RA=0 should map to ecliptic (0, 0).
    #[test]
    fn equatorial_to_ecliptic_origin() {
        let (lon, lat) = equatorial_to_ecliptic(0.0, 0.0);
        assert!(lon.abs() < 0.01 || (lon - 360.0).abs() < 0.01);
        assert!(lat.abs() < 0.01);
    }
}
